import React,{useEffect,useState}from'react';
import{createRoot}from'react-dom/client';
import{createPortal}from'react-dom';
import{motion}from'framer-motion';
import{ArrowLeft,ArrowRight,Award,Check,ChevronDown,Files,FolderSearch,History,KeyRound,Menu,MessageSquareMore,Search,Target,Volume2,VolumeX,X}from'lucide-react';
import{useLessonAudio}from'../../shared/useLessonAudio';
import'./styles.css';
import hookArt from'./assets/illustrations/hook-unfindable-artifact.png';
import hookModalArt from'./assets/illustrations/modal-findable-path.png';
import accessArt from'./assets/illustrations/accessibility-four-practices.png';
import effectiveArt from'./assets/illustrations/effectiveness-feedback-loop.png';
import tailoringArt from'./assets/illustrations/modal-tailoring-actions.png';
import examArt from'./assets/illustrations/exam-retrospective-artifact.png';
import examModalArt from'./assets/illustrations/modal-exam-accessibility.png';

const tabs=['The hidden cost','Engineer access','Test effectiveness','Exam lens'];
const accessItems=[
 ['Single Source of Truth','One authoritative location per artifact — links, not copies. The fastest way to destroy data trust is two versions of the risk register floating around.',Files],
 ['Version Control and Naming Discipline','The current version stays unambiguous, history is preserved, and baselines are locked once set — nobody guessing which file is actually current.',History],
 ['Role-Appropriate Access','The franchisee representative reads the status pack without editing the cost workbook; the auditor reaches the evidence pack without asking five people for it.',KeyRound],
 ['Findability at Point of Need','Structure mirrors how people actually search — by deliverable, by meeting, by decision — not by who happened to create the folder in week two.',FolderSearch]
];
const effectiveItems=[
 ['A Register Nobody Has Opened in Three Weeks',"If nobody's looking at it, it isn't informing any decision — it's just accumulating.",FolderSearch],
 ['A Report Produced but Never Discussed','Effort spent generating something nobody engages with is effort spent on ceremony, not on decision-making.',MessageSquareMore],
 ['A Log Back-Filled Before Audits','If the record only gets accurate right before someone checks it, it was never actually being used day to day.',History],
 ['Duplicate Trackers Spawning in Chat Tools','When the official artifact is too slow or too cumbersome, people quietly route around it — and that workaround itself is a signal the system needs attention.',Files]
];
const reveals={
 hook:{image:hookModalArt,title:"Building the artifact was never the finish line.",text:"This task combines two enablers: helping ensure accessibility of artifacts, and continually assessing whether artifact management is actually working. Building the artifact was never the finish line. If nobody can find it, or nobody's checking whether the whole system of registers and reports is actually earning its keep, the effort behind it evaporates quietly, one unread document at a time."},
 response:{image:tailoringArt,title:"The professional responses are tailoring moves.",text:'The professional responses are tailoring moves — merge, simplify, automate, or retire — executed deliberately and recorded in the decision log. Retrospectives are the natural venue for this: "is our information system serving us?" belongs on the agenda as much as "is our code quality holding?"'},
 exam:{image:examModalArt,title:'Accessibility and effectiveness work together.',text:'Accessibility is engineered through four practices: a single source of truth, version control and naming discipline, role-appropriate access, and findability at point of need. Effectiveness is the feedback loop that periodically interrogates whether the artifact machinery is actually helping the project decide, or merely accumulating — watching for signals like an unopened register, an undiscussed report, a back-filled log, or duplicate trackers spawning outside the official system. The professional response to those signals is a deliberate tailoring move — merge, simplify, automate, or retire — recorded in the decision log, with retrospectives as the natural place to ask the question out loud.',bullets:['Four accessibility practices: single source of truth, version control/naming discipline, role-appropriate access, findability at point of need','"Links, not copies" — two actively maintained versions of the same artifact destroys data trust','Four effectiveness signals: unopened register, undiscussed report, back-filled log, duplicate trackers in chat tools','Professional response to those signals: merge, simplify, automate, or retire — deliberate, recorded, and raised in retrospectives']}
};
const quizzes={
 access:{question:'Scenario: Two separate copies of the risk register exist — one maintained by the PM in the PMIS, another kept in a shared spreadsheet by a team lead who finds the PMIS slow to update. Both are actively edited. What accessibility practice does this violate?',answers:["Role-appropriate access, since the team lead shouldn't have edit rights",'Single source of truth — two actively maintained copies of the same artifact is exactly what destroys data trust','Findability at point of need, since the spreadsheet is harder to search','Version control, since the spreadsheet lacks a formal naming convention'],correct:1,good:'Right — this is the textbook single-source-of-truth violation: two actively edited copies of the same artifact, with no way to know which one reflects reality. Links, not copies, is the fix.',bad:'Reconsider — the core problem here is that two separate, independently edited copies of the same artifact both exist and are both being trusted, not who has access or how easy either one is to search.'},
 effective:{question:"Scenario: A project's official risk register is updated weekly, but the delivery team has quietly started maintaining its own risk list in a shared chat channel because the official register takes too long to update and doesn't reflect day-to-day blockers. What does this situation best indicate?",answers:['The delivery team is being non-compliant and should be instructed to stop using the chat channel immediately','A signal that the artifact system needs a tailoring response — the official register may need to be simplified or the process automated, addressed deliberately and recorded in the decision log','A findability problem, since the delivery team can’t locate the official register','A version control issue, since two different naming conventions are now in use'],correct:1,good:"Correct! A duplicate tracker spawning in a chat tool is exactly the kind of signal enabler 9.8 is built to catch — it means the official artifact isn't serving the people who need it day to day, and the professional response is a deliberate tailoring move, not just a compliance instruction.",bad:"Reconsider — this isn't about locating the register or naming conventions; it's specifically the duplicate-tracker-in-chat pattern that signals the official system needs to be merged, simplified, automated, or retired."}
};
function Modal({data,onClose,onDone}){const[step,setStep]=useState(0);useEffect(()=>{const key=e=>e.key==='Escape'&&onClose();addEventListener('keydown',key);return()=>removeEventListener('keydown',key)},[onClose]);return createPortal(<div className="modal-backdrop" onClick={onClose}><motion.section className="focus-modal" initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} onClick={e=>e.stopPropagation()}><button className="modal-x" onClick={onClose} aria-label="Close"><X/></button>{step===0?<><img className="modal-illustration" src={data.image}/><h3>{data.title}</h3><div className="modal-copy"><p>{data.text}</p></div></>:<div className="memory-step"><p className="eyebrow">EXAM-RELEVANT ENABLERS TO REMEMBER</p><h3>Make artifacts accessible and useful.</h3><ul>{data.bullets.map(item=><li key={item}>{item}</li>)}</ul></div>}{data.bullets&&step===0?<button className="modal-action" onClick={()=>setStep(1)}>Next <ArrowRight/></button>:<button className="modal-action" onClick={onDone}>Mark as read <Check/></button>}</motion.section></div>,document.body)}
function Quiz({data,onFinish}){const[picked,setPicked]=useState(null);return createPortal(<div className="knowledge-backdrop"><section className="knowledge-modal"><p className="quiz-label"><Target/> MICRO KNOWLEDGE CHECK</p><h3>{data.question}</h3><div className="answers">{data.answers.map((answer,i)=><button key={answer} className={picked===i?(i===data.correct?'correct':'wrong'):''} onClick={()=>setPicked(i)}><span>{String.fromCharCode(65+i)}</span>{answer}</button>)}</div>{picked!==null&&<><p className={`feedback ${picked===data.correct?'good':'bad'}`}>{picked===data.correct?data.good:data.bad}</p><button className="finish-check" onClick={onFinish}>Finish check <ArrowRight/></button></>}</section></div>,document.body)}
function AccordionPage({eyebrow,title,lead,art,items,open,setOpen,read,setRead,after}){return <div className="wide-page"><div className="section-intro"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2><p className="lead">{lead}</p></div><img className="section-art" src={art}/></div><div className="accordion">{items.map(([name,text,Icon],i)=><div className={`accordion-item ${open===i?'open':''}`} key={name}><button onClick={()=>{setOpen(i);setRead(values=>values.map((v,j)=>j===i?true:v))}}><span className="category-icon"><Icon/></span><span className="category-number">0{i+1}</span><strong>{name}</strong><ChevronDown/></button>{open===i&&<div className="accordion-copy"><p>{text}</p></div>}</div>)}</div>{read.every(Boolean)&&after}</div>}
function App(){const[page,setPage]=useState(0),[done,setDone]=useState(Array(4).fill(false)),[modal,setModal]=useState(null),[quiz,setQuiz]=useState(null),[sound,setSound]=useState(true);const[aOpen,setAOpen]=useState(0),[aRead,setARead]=useState([true,false,false,false]);const[eOpen,setEOpen]=useState(0),[eRead,setERead]=useState([true,false,false,false]);useLessonAudio(sound);const mark=i=>setDone(v=>v.map((x,j)=>j===i?true:x));const go=i=>{if(i>=0&&i<4&&(i<=page+1||done[i-1]))setPage(i)};const finishModal=()=>{mark(page);setModal(null)};let content;
if(page===0)content=<div className="hero-layout"><div><p className="eyebrow">LESSON 5.1.3 · ACCESSIBILITY AND EFFECTIVENESS</p><h1>An artifact nobody can find <span>is functionally identical to an artifact that doesn't exist.</span></h1><p className="lead">Except it also cost money.</p><button className="primary-cta" disabled={done[0]} onClick={()=>setModal('hook')}>{done[0]?'Critical signal revealed':'Reveal the hidden cost'} <ArrowRight/></button></div><img className="lesson-art" src={hookArt}/></div>;
if(page===1)content=<AccordionPage eyebrow="ACCESSIBILITY: ENGINEERED, NOT ASSUMED" title="Accessibility is engineered through four practices." lead="Accessibility — enabler 9.4 — isn't a hope that people will eventually find what they need. It's engineered, typically in the PMIS, through four specific practices. Click each to explore." art={accessArt} items={accessItems} open={aOpen} setOpen={setAOpen} read={aRead} setRead={setARead} after={!done[1]&&<button className="knowledge-cta" onClick={()=>setQuiz('access')}><Target/> Start knowledge check <ArrowRight/></button>}/>;
if(page===2)content=<AccordionPage eyebrow="EFFECTIVENESS: THE SYSTEM'S FEEDBACK LOOP" title="Is any of this actually helping us decide anything?" lead={'Enabler 9.8 asks a different question than accessibility does — not "can people find it," but "is any of this actually helping us decide anything?" Click each signal to explore.'} art={effectiveArt} items={effectiveItems} open={eOpen} setOpen={setEOpen} read={eRead} setRead={setERead} after={!done[2]&&<button className="primary-cta" onClick={()=>setModal('response')}>Reveal the response <ArrowRight/></button>}/>;
if(page===3)content=<div className="exam-layout"><div className="exam-visual"><img src={examArt}/></div><div><p className="eyebrow">SYNTHESIS (EXAM LENS)</p><h2>Every decision made without it.</h2><p className="lead">Back to that unfindable artifact one more time — because the cost was never just the time spent creating it. It was every decision made without it.</p><button className="primary-cta" disabled={done[3]} onClick={()=>setModal('exam')}>{done[3]?'Exam lens reviewed':'Reveal the exam lens'} <ArrowRight/></button></div></div>;
return <div className="app-shell"><header className="topbar"><button className="course-select"><Award/><span>PMP Project Management Professional</span><ChevronDown/></button><div className="module-progress"><div>{Array.from({length:10},(_,i)=><span className={`progress-dot ${i<3?'done':i===3?'active':''}`} key={i}>{i<3?<Check size={10}/>:<span/>}</span>)}</div></div><div className="top-actions"><button className="ghost-button" onClick={()=>setSound(v=>!v)}>{sound?<Volume2/>:<VolumeX/>}<span>{sound?'Sound on':'Sound off'}</span></button><button className="ghost-button"><X/><span>Quit</span></button></div></header><main className="workspace"><section className="lesson-stage"><div className="outline"><button className="menu-button"><Menu/></button></div><article className="lesson-card"><div className="section-tabs"><p>SECTION {page+1} OF 4</p><div>{tabs.map((tab,i)=><button key={tab} className={`${done[i]?'done':''} ${page===i?'active':''}`} onClick={()=>go(i)}>{done[i]&&<Check/>}{tab}</button>)}</div></div><div className="lesson-content">{content}</div>{done[page]&&<p className="completion"><Check/> Interaction complete — continue when ready.</p>}<footer className="nav-footer"><button className="secondary-button" disabled={!page} onClick={()=>go(page-1)}><ArrowLeft/> Previous</button><button className={`primary-button ${done[page]?'unlocked':''}`} disabled={!done[page]} onClick={()=>page<3&&go(page+1)}>{page===3?'Continue to next lesson':'Continue'} <ArrowRight/></button></footer></article></section></main>{modal&&<Modal data={reveals[modal]} onClose={()=>setModal(null)} onDone={()=>{if(modal==='response'){setModal(null);setQuiz('effective')}else finishModal()}}/>}{quiz&&<Quiz data={quizzes[quiz]} onFinish={()=>{mark(page);setQuiz(null)}}/>}</div>}
createRoot(document.getElementById('root')).render(<App/>);
